version: '3'
services:
  web:
    build:
        context: ./build/nginx
    image: ex3-nginx:latest
    container_name: ex3-nginx
    ports:
       - "80:80"
    volumes:
       - ./src/:/home/ex3/public_html/
       - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
    restart: always

  php:
    build:
        context: ./build/php-fpm
    image: ex3-fpm
    container_name: ex3-fpm
    volumes:
        - ./src/:/home/ex3/public_html/
        - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./conf/php/upload.ini:/usr/local/etc/php/conf.d/upload.ini
    restart: always