version: '3'
services:
  web:
    build:
        context: ./build/nginx
#    image: ex1:latest
#    container_name: ex1
    ports:
       - "80:80"
    volumes:
       - ./src/:/home/ex2/public_html/
       - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./conf/nginx/conf.d/:/etc/nginx/conf.d/